# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64aca75644dce61eb29a65bd5d4b1d4c25a9b4001c19d1becc16c3093ebc1a5eb22fb5428e304d7edd07e1a43194ccbee03ffcf6e4aad7aed2709f81993fe314

test:
  secret_key_base: 61e8520cce7a15964ccc1b70d62b737663fd9ca742d4ea0203e6fc3054b4d715987718d260916a28a74a7a9456bc07afdebfff00921b6802ffc7d1ea3134efd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
